mod agent_action;
mod broadcast;
pub(crate) mod capability;
mod config;
mod connect;
mod discover;
mod input;
mod manpage;
mod mcp;
mod plan;
pub(crate) mod proxy;
pub(crate) mod relay;
mod review;
mod serve;
mod session;
mod skills;
mod usage;
mod user;

pub(crate) use agent_action::{AgentActionParams, run_agent_action};
pub(crate) use broadcast::{BroadcastParams, run_broadcast};
pub(crate) use config::run_config;
pub(crate) use connect::{run_connect, run_disconnect};
pub(crate) use discover::run_discover;
pub(crate) use input::{InputParams, run_input};
pub(crate) use manpage::{HELP_AGENT, print_manpage};
pub(crate) use mcp::run_mcp;
pub(crate) use plan::{PlanParams, run_plan};
pub(crate) use relay::{RelayParams, run_relay};
pub(crate) use review::{ReviewParams, run_review};
pub(crate) use serve::{ServeParams, run_serve};
pub(crate) use session::run_session;
pub(crate) use skills::run_skills;
pub(crate) use usage::run_usage;
pub(crate) use user::run_user;
